#!/usr/bin/env ruby

require 'yaml'
require 'slim'

class Section
  attr_reader :head, :eqs

  def initialize(head, eqs)
    @head = "<h1>#{head}</h1>"
    @eqs = eqs.map &method(:format)
  end

  def to_s
    @head + @eqs.join()
  end

  private

  def format(eq) "<p>\\[#{eq}\\]</p>" end

end

sections = YAML.load_file('eqs.yml').map { |head, eqs| Section.new(head,eqs) }

template = Slim::Template.new('layout.slim')

File.open('index.html', 'w+') do |f|
  f.write template.render(Object.new, sections: sections)
end
